development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: painkiller778
  :password: rootadmin@painkiller
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: painkiller778
  :password: rootadmin@painkiller
  :enable_starttls_auto: true